[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Wind-AE"
authors = [{name = "Madelyn Broome", email = "mabroome@ucsc.edu"}]
dynamic = ["version", "description"]
